development:
  adapter: postgresql
  database: thats_my_bike_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: thats_my_bike_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: thats_my_bike_production
  pool: 5
  timeout: 5000
